# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI task for pre-prod branch

on:
  push:
    branches: [ pre-prod ]
  pull_request:
    branches: [ pre-prod ]

jobs:
  build_app:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - run: echo "Install mocha JavaScript test framework for Node.js"
    - run: npm i -g mocha
    - run: echo "Install dependencies"
    - run: npm install
    - run: echo "Install unit testing framework"
    - run: npm install unit.js
    - run: echo "Clean install of your dependencies"
    - run: npm ci
    - run: echo "Build your package"
    - run: npm run build --if-present
    - run: echo "Test your app"
    - run: mocha test.js
